### PR TITLE
feat: add Client function to create custom image service

### PR DESCRIPTION
**Pull request by incubator4**
#### Description (required)
Add `Client` function `CreateCustomService` to create custom image service

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by pan93412** [comment]
Thanks a lot to your contribution!

Most of them seem great. However, I would prefer to pass the TOML into createPrebuiltService using the rawSchema parameter. CLI users usually prefer to use their existing Prebuilt TOML definitions, like [this PostgreSQL TOML definition](https://github.com/zeabur/zeabur/blob/main/prebuilts/postgresql.toml).

The GraphQL mutation of this method is:

```graphql
mutation CreatePrebuiltService($projectId: ObjectID!, $rawSchema: String) {
  createPrebuiltService(projectID: $projectId, rawSchema: $rawSchema) {
    _id
  }
}
```

**Comment by incubator4** [comment]
> Thanks a lot to your contribution!
> 
> Most of them seem great. However, I would prefer to pass the TOML into createPrebuiltService using the rawSchema parameter. CLI users usually prefer to use their existing Prebuilt TOML definitions, like [this PostgreSQL TOML definition](https://github.com/zeabur/zeabur/blob/main/prebuilts/postgresql.toml).
> 
> The GraphQL mutation of this method is:
> 
> ```graphql
> mutation CreatePrebuiltService($projectId: ObjectID!, $rawSchema: String) {
>   createPrebuiltService(projectID: $projectId, rawSchema: $rawSchema) {
>     _id
>   }
> }
> ```

which means just need to marshal struct to json string ?

**Comment by pan93412** [comment]
The general flow of this method would be "Read service.toml", then put the TOML in the parameter.

---

理論上是讀 service.toml 然後把 TOML 放進去 schemaRaw 裡面。

**Comment by incubator4** [comment]
In some case, what if I just want to use cli package as sdk, it would be more helpful like this.
Although using cli as SDK is not so good, there is currently no package like `zeabur/sdk` 
```go
package main

import (
	"context"
	"fmt"
	"github.com/zeabur/cli/pkg/api"
	"github.com/zeabur/cli/pkg/model"
	"os"
)

func main() {
	ctx := context.Background()
	token := os.Getenv("ZEABUR_API_TOKEN")
	client := api.New(token)

	project, err := client.GetProject(ctx, "", "incubator4", "togitic")
	if err != nil {
		panic(err)
	}

	schema := model.ServiceSpecSchemaInput{
		ID:   "httpbin",
		Name: "httpbin",
		Source: &model.ServiceSpecSourceInput{
			Image: "kennethreitz/httpbin",
		},
	}
	service, err := client.CreateCustomService(ctx, project.ID, schema)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Service: %+v\n", service)
}
```

**Comment by pan93412** [comment]
> In some case, what if I just want to use cli package as sdk, it would be more helpful like this. Although using cli as SDK is not so good, there is currently no package like `zeabur/sdk`
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 	"github.com/zeabur/cli/pkg/api"
> 	"github.com/zeabur/cli/pkg/model"
> 	"os"
> )
> 
> func main() {
> 	ctx := context.Background()
> 	token := os.Getenv("ZEABUR_API_TOKEN")
> 	client := api.New(token)
> 
> 	project, err := client.GetProject(ctx, "", "incubator4", "togitic")
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	schema := model.ServiceSpecSchemaInput{
> 		ID:   "httpbin",
> 		Name: "httpbin",
> 		Source: &model.ServiceSpecSourceInput{
> 			Image: "kennethreitz/httpbin",
> 		},
> 	}
> 	service, err := client.CreateCustomService(ctx, project.ID, schema)
> 	if err != nil {
> 		panic(err)
> 	}
> 	fmt.Printf("Service: %+v\n", service)
> }
> ```

Understand. Seems reasonable. I will approve this.

**Review by pan93412 — APPROVED** [review]

**Comment by incubator4** [comment]
@pan93412 An additional update, rawSchema also be added to Client interface

**Comment by pan93412** [comment]
"RawService" seems weird. How about "CreatePrebuiltServiceRaw" and "CreatePrebuiltServiceCustom"?

**Comment by incubator4** [comment]
> "RawService" seems weird. How about "CreatePrebuiltServiceRaw" and "CreatePrebuiltServiceCustom"?

function name updated

**Review by yuaanlin — APPROVED** [review]

**Pull request merged**
